[versions]
agp = "9.0.1"
kotlin = "2.3.10"
ksp = "2.3.5"
daggerHilt = "2.59.1"
daggerHiltLifecycleCompose = "1.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
composeUi = "1.10.2"
composeMaterial3 = "1.5.0-alpha13"
composeFoundation = "1.10.3"
navigation3 = "1.0.0"
kotlinxSerialization = "1.10.0"
ktor = "3.4.0"
ktlint = "1.8.0"
ktlintGradle = "14.0.1"
detekt = "1.23.8"
detektCompose = "0.5.6"
smbj = "0.14.0"
rapid7Dcerpc = "0.12.13"
datastore = "1.2.0"
androidxDocumentfile = "1.1.0"
protobuf = "4.33.5"
protobufPlugin = "0.9.6"
coil = "2.7.0"
zoomable = "2.10.0"
jakartaInject = "2.0.1"
microsoftGraph = "6.60.0"
azureIdentity = "1.18.2"
workManager = "2.11.1"
room = "2.8.4"

[libraries]
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxJunit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidxEspressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidxLifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidxLifecycleViewmodelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidxLifecycleViewmodelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidxLifecycleViewmodelNavigation3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycleRuntimeKtx" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidxComposeUi = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
androidxComposeUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeUi" }
androidxComposeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeUi" }
androidxComposeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeUi" }
androidxComposeUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeUi" }
androidxComposeUiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeUi" }
androidxComposeMaterial3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
androidxComposeFoundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "composeFoundation" }
androidxNavigation3Runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
androidxNavigation3Ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
hiltCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "daggerHilt" }
hiltLifecycleViewmodelCompose = { group = "androidx.hilt", name = "hilt-lifecycle-viewmodel-compose", version.ref = "daggerHiltLifecycleCompose" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ktorClientCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorClientCio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktorClientContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorSerializationKotlinxJson = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
# 自動アップデートの為に定義している
ktlintCli = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }
detektCompose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detektCompose" }
smbj = { group = "com.hierynomus", name = "smbj", version.ref = "smbj" }
smbjRpc = { group = "com.rapid7.client", name = "dcerpc", version.ref = "rapid7Dcerpc" }
androidxDatastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
androidxDocumentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidxDocumentfile" }
protobufKotlinLite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobufProtoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
coilCompose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
zoomable = { group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable" }
jakartaInject = { group = "jakarta.inject", name = "jakarta.inject-api", version.ref = "jakartaInject" }
microsoftGraph = { group = "com.microsoft.graph", name = "microsoft-graph", version.ref = "microsoftGraph" }
azureIdentity = { group = "com.azure", name = "azure-identity", version.ref = "azureIdentity" }
androidxWorkManagerRuntime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
androidxWorkManagerHilt = { group = "androidx.hilt", name = "hilt-work", version.ref = "daggerHiltLifecycleCompose" }
androidxHiltCompiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "daggerHiltLifecycleCompose" }
androidxRoomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidxRoomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidxRoomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
